class Daftar {
  final String anime;
  final String studio;
  final String gambar;
  final String desk;

  Daftar(
    this.anime,
    this.studio,
    this.gambar,
    this.desk,
  );
}

List daftar = [
  Daftar('Sousou no frieren', 'Mad House', 'folder/images/frieren.jpg', '"Sousou no Frieren" adalah cerita tentang Frieren, seorang penyihir, yang menyaksikan teman-temannya yang menjadi pahlawan perlahan-lahan meninggal setelah mengalahkan raja iblis. Sebelum dia juga meninggal, dia mengambil seorang manusia magang bernama Fern untuk mengumpulkan mantra sihir. Mereka berdua melakukan perjalanan ke tempat-tempat yang pernah dikunjungi oleh para pahlawan dahulu kala. Selama perjalanan mereka, Frieren merenungkan penyesalannya atas kehilangan peluang untuk membentuk ikatan yang lebih dalam dengan teman-temannya yang telah meninggal.'),
  Daftar('Re zero', 'White Fox', 'folder/images/rezero.jpg', '"Re:Zero - Starting Life in Another World" mengikuti perjalanan Natsuki Subaru, seorang pemuda yang terlempar ke dunia fantasi dan memiliki kemampuan untuk hidup kembali setelah mati, tetapi dengan harga yang mahal. Dia berjuang untuk melindungi teman-temannya dan mengungkap berbagai teka-teki dalam dunia yang berbahaya, sambil mencoba untuk mengatasi takdir tragis yang terus menghantuinya.'),
  Daftar('Overlord', 'Mad House', 'folder/images/Overlord.jpg', '"Overlord" adalah anime yang mengisahkan tentang Suzuki Satoru, seorang pemain yang setia bermain dalam permainan daring yang populer bernama Yggdrasil. Namun, ketika permainan ini akan ditutup, Satoru menemukan bahwa karakternya, Momonga, tidak log out seperti pemain lainnya. Dia terjebak dalam dunia permainan dengan karakternya yang kuat, dan tanpa ada cara untuk kembali ke dunia nyata. Dalam upayanya untuk memahami situasinya, Momonga memutuskan untuk menjelajahi dunia baru ini dan mencari tahu apakah ada pemain lain yang juga terjebak. Seiring perjalanan Momonga, dia menjadi Overlord yang kuat dan berusaha mendominasi dunia fantasi ini dengan mengendalikan guild-nya yang terdiri dari NPC (Non-Player Character) yang memiliki kepribadian dan kecerdasan sendiri. Anime ini menggabungkan unsur-unsur aksi, fantasi, dan strategi politik yang kompleks.'),
  Daftar('Naruto', 'Pierrot', 'folder/images/naruto.jpg', '"Naruto" adalah kisah tentang seorang ninja muda bernama Naruto Uzumaki yang bermimpi menjadi Hokage, pemimpin desa ninja terkuat. Dengan tekad yang kuat dan semangat yang tak tergoyahkan, Naruto berjuang melalui berbagai ujian, pertarungan sengit, dan rintangan emosional untuk mencapai mimpinya. Selama perjalanan ini, dia membangun persahabatan yang kuat, mengungkap misteri tentang masa lalunya, dan berkontribusi dalam melindungi desanya dari berbagai ancaman. Naruto menjadi ikon dalam dunia anime dan manga, tidak hanya karena pertarungannya yang epik tetapi juga karena pesan-pesan kuat tentang persahabatan, ketekunan, dan perubahan diri yang ada dalam ceritanya.'),
  Daftar('Durarara', 'Brains Base', 'folder/images/durarara.jpg', '"Durarara!!" adalah kisah yang berpusat di Ikebukuro, Tokyo, yang dihuni oleh berbagai karakter eksentrik dan misterius. Dengan intrik, konspirasi, dan kekuatan supernatural yang merajalela, cerita ini mengikuti perjalanan Mikado Ryuugamine, Masaomi Kida, Celty Sturluson, dan banyak karakter lainnya saat mereka terlibat dalam jaringan hubungan yang rumit dan memecahkan misteri kota yang semakin aneh. Dengan plot yang kompleks dan beragam tema seperti identitas, kebebasan, dan konsekuensi dari tindakan manusia, "Durarara!!" adalah anime yang penuh aksi dan misteri yang membuat penonton terus ingin tahu.'),
  Daftar('Chainsaw Man', 'Mappa', 'folder/images/chainsaw.jpg', '"Chainsaw Man" adalah cerita manga yang mengikuti perjalanan Denji, seorang pemuda miskin yang terpaksa berburu iblis dengan bantuan iblisnya sendiri yang berwujud gergaji mesin, Chainsaw Man. Setelah mengalami nasib buruk sepanjang hidupnya, Denji mengejar harapannya untuk hidup yang lebih baik sebagai pemburu iblis yang disewa oleh pemerintah. Cerita ini penuh dengan aksi yang brutal, pertempuran melawan iblis mengerikan, dan konflik antara iblis dan pemburu iblis. Sementara itu, Denji berusaha untuk memahami makna hidup dan mengatasi masa lalunya yang kelam dalam perjalanan yang penuh dengan keputusan sulit dan pengorbanan. "Chainsaw Man" dikenal karena gaya naratifnya yang gelap, darah, dan cerita yang menggugah pemikiran tentang eksistensi dan kemanusiaan.'),
  Daftar('Bleach', 'Pierrot', 'folder/images/blaech.jpg', '"Bleach" adalah manga dan anime yang mengisahkan Ichigo Kurosaki, seorang remaja dengan kemampuan melihat arwah. Namun, hidupnya berubah drastis ketika ia tanpa sengaja mendapatkan kekuatan Shinigami (Dewa Kematian) dari seorang Shinigami bernama Rukia Kuchiki. Ichigo terlibat dalam pertempuran melawan roh jahat yang disebut Hollows dan menemukan dirinya terlibat dalam konflik yang lebih besar antara Shinigami dan kekuatan gelap yang mengancam kedamaian dunia. Dalam perjalanannya, Ichigo bertemu dengan berbagai karakter kuat, menghadapi musuh yang menakutkan, dan mengungkap misteri keluarganya sendiri. "Bleach" dikenal dengan pertarungan epik dan pengembangan karakter yang mendalam serta eksplorasi tema-tema seperti pertemanan, keberanian, dan tanggung jawab.')
];